export const ScreenNamesMarketing = {
  DASHBOARD: 'Dashboard',
  ORDERS: 'Orders',
  DISPATCHES: 'Dispatches',
  RECEIPTS: 'Receipts',
  APPOINTMENTS: 'Appointments',
  CUSTOMERS: 'Customers',
  GALLERIES: 'Galleries',
  MYPROFILE: 'MyProfile',
  ORDERPRODUCTSEARCH: 'OrdersProductSearch',
  ORDERPRODUCTDETAILS: 'OrdersProductDetails',
  ORDERCARTDETAILS: 'OrderCartDetails',
  ORDERAVAILABILITYCHECK: 'OrderAvailabilityCheck',
  ORDERPRODUCTDELIVERYSTATUS: 'OrderProductDeliveryStatus',
  ORDERDETAILSVIEW: 'OrderDetailsView',
  ORDERUPDAATE: 'OrderUpdate',
  DISPATCHORDERLIST: 'DispatchOrderList',
  DISPATCHCUSTOMERLIST: 'DispatchCustomerList',
  DISPATCHDETAILS: 'DispatchDetails',
  DISPATCHTRACKSTATUS: 'DispatchTrackStatus',
  CUSTOMERNAMESEARCH: 'CustomerNameSearch',
  ORDERSLIST: 'OrdersList',
  CREATERECEIPT: 'CreateReceipt',
  EDITRECEIPT: 'EditReceipt',
  VIEWRECEIPT: 'ViewReceipt',
  RECEIPTSLIST: 'ReceiptsList',
  CUSTOMERDETAILSUPDATE: 'CustomerDetailsUpdate',
  CUSTOMERAPPOINTMENTANDORDER: 'CustomerAppointmentAndOrder',
  CUSTOMERORDERFLOWSTATUS: 'CustomerOrderFlowStatus',
  GALLERYDETAILVIEW: 'GalleryDetailView',
  CREATEAPPOINTMENTS: 'CreateAppointments',
  UPDATEAPPOINTMENTS: 'UpdateAppointments',
  SHOWBRANDS: 'ShowBrands',
  SHOWCATEGORIES: 'ShowCategories',
  PRODUCTDETAILS: 'ProductDetails',
  PRODUCTDETAILSFROMSEARCH: 'ProductDetailsFromSearch',
};

export const ScreenNamesGeneral = {
  LOGIN: 'Login',
};
