export const ScreenNamesMarketing = {
  DASHBOARD: 'Dashboard',
  ORDERS: 'Orders',
  DISPATCHES: 'Dispatches',
  RECEIPTS: 'Receipts',
  APPOINTMENTS: 'Appointments',
  CUSTOMERS: 'Customers',
  GALLERIES: 'Galleries',
  MYPROFILE: 'MyProfile',
  ORDERPRODUCTSEARCH: 'OrdersProductSearch',
  ORDERPRODUCTDETAILS: 'OrdersProductDetails',
  ORDERCARTDETAILS: 'OrderCartDetails',
  ORDERAVAILABILITYCHECK: 'OrderAvailabilityCheck',
  ORDERPRODUCTDELIVERYSTATUS: 'OrderProductDeliveryStatus',
  ORDERDETAILSVIEW: 'OrderDetailsView',
  ORDERUPDAATE: 'OrderUpdate',
  DISPATCHORDERLIST: 'DispatchOrderList',
  DISPATCHCUSTOMERLIST: 'DispatchCustomerList',
  DISPATCHDETAILS: 'DispatchDetails',
  DISPATCHTRACKSTATUS: 'DispatchTrackStatus',
  CUSTOMERNAMESEARCH: 'CustomerNameSearch',
  ORDERSLIST: 'OrdersList',
  RECEIPTORDERDETAILS: 'ReceiptOrderDetails',
  CUSTOMERDETAILSUPDATE: 'CustomerDetailsUpdate',
  CUSTOMERAPPOINTMENTANDORDER: 'CustomerAppointmentAndOrder',
  CUSTOMERORDERFLOWSTATUS: 'CustomerOrderFlowStatus',
  GALLERYDETAILVIEW: 'GalleryDetailView',
};

export const ScreenNamesGeneral = {
  LOGIN: 'Login',
};
