import {Dimensions} from 'react-native';
import {colors} from './colors';

const {width} = Dimensions.get('window');

export const viewStyles = {
  flex: {
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: colors.DEFAULT_BACKGROUND_COLOR,
  },
  restContainer: {
    flex: 1,
    backgroundColor: colors.WHITE_SNOW,
  },
  textInputStyles: {
    marginHorizontal: 35,
    height: 56,
    borderRadius: 5,
    borderColor: colors.TEXT_INPUT_BORDER_COLOR,
    borderWidth: 1.5,
    paddingLeft: 16,
    fontSize: 17,
    lineHeight: 22,
    color: colors.BLACK,
  },
  headerTextStyles: {
    marginTop: 16,
    marginHorizontal: 35,
    color: colors.RED,
    fontSize: 15,
    lineHeight: 20,
    letterSpacing: -0.24,
    marginBottom: 5,
  },
  buttonStyles: {
    marginHorizontal: 35,
    marginTop: 16,
    borderRadius: 10,
    height: 50,
    backgroundColor: colors.RED,
  },
  activityIndicatorStyles: {
    position: 'absolute',
    backgroundColor: colors.SEPERATOR_COLOR,
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorTextStyles: {
    fontSize: 14,
    lineHeight: 19,
    letterSpacing: -0.24,
    marginTop: 25,
    color: colors.WHITE,
    backgroundColor: colors.RED,
    marginTop: 50,
  },
  textDashboardHeaderStyles: {
    marginTop: 54,
    height: 20,
    fontSize: 17,
    lineHeight: 22,
    fontWeight: '600',
    color: colors.RED,
  },
  headerDashboardStyles: {
    width: width,
    height: 88,
    backgroundColor: 'white',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: colors.BLACK_WITH_OPACITY_3,
  },
  separatorStyle: {
    backgroundColor: colors.BLACK,
    height: 1,
    marginHorizontal: 0,
    marginTop: 26,
    opacity: 0.1,
  },
  listRowViewStyle: {
    marginLeft: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.BLACK_WITH_OPACITY_3,
  },
  commonTextStyles: {
    paddingVertical: 11,
    fontSize: 17,
    lineHeight: 22,
    letterSpacing: -0.408,
    color: colors.BLACK,
  },
  orderTitleStyles: {
    paddingVertical: 13,
    fontSize: 17,
    lineHeight: 22,
    letterSpacing: -0.5,
    color: colors.PAYNE_GREY,
    opacity: 0.5,
  },
  viewCommonStyle: {
    marginLeft: 16,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    borderBottomColor: colors.BLACK_WITH_OPACITY_1,
    borderBottomWidth: 1,
  },
  descriptionStyles: {
    fontSize: 13,
    lineHeight: 18,
    letterSpacing: -0.078,
    color: colors.PAYNE_GREY_OPACITY,
    paddingTop: 6,
    paddingHorizontal: 16,
    paddingBottom: 14,
  },
  viewMainStyles: {
    marginHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  galleryTextStyles: {
    fontWeight: '400',
    fontSize: 21,
    letterSpacing: -0.078,
    color: colors.WHITE,
    marginTop: 25,
    marginLeft: 21,
    marginRight: 50,
  },
  galleryDescriptionStyles: {
    fontSize: 19,
    lineHeight: 18,
    letterSpacing: -0.078,
    color: colors.WHITE,
    marginTop: 11,
    marginLeft: 21,
    opacity: 0.5,
  },
  galleryMenuBigIconStyle: {
    position: 'absolute',
    top: 15,
    right: 14,
    width: 32,
    height: 32,
  },
  galleryRowOverlayView: {
    position: 'absolute',
    top: 0,
    right: 0,
    left: 0,
    bottom: 0,
    backgroundColor: colors.BLACK_RUSSIAN,
    opacity: 0.4,
  },
  galleryMenuSmallIconStyle: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 18,
    height: 18,
  },
  galleryDetailsRowStyle: {
    marginBottom: 10,
    borderRadius: 13,
    overflow: 'hidden',
    marginRight: 6,
  },
  galleryDetailsFlatListStyles: {
    flex: 1,
    marginTop: 8,
    marginBottom: 0,
    marginHorizontal: 10,
  },
  headerTextStyle: {
    marginTop: 54,
    height: 20,
    fontSize: 17,
    lineHeight: 22,
    fontWeight: '600',
    color: colors.RED,
  },
  headerMainStyles: {
    width: width,
    height: 88,
    backgroundColor: colors.WHITE,
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: colors.BLACK_WITH_OPACITY_3,
  },
  headerLeftTextStyle: {
    fontSize: 17,
    lineHeight: 22,
    letterSpacing: -0.408,
    color: colors.VIVID_BLUE,
    marginLeft: 4,
    marginTop: 7,
    color: colors.RED,
  },
  headerRightTextStyle: {
    marginTop: 54,
    fontSize: 17,
    lineHeight: 22,
    fontWeight: '600',
    marginRight: 26,
    color: colors.VIVID_BLUE,
    height: 44,
    color: colors.RED,
  },
  flexDirection: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  customerRowTextStyles: {
    marginLeft: 16,
    fontSize: 16,
    lineHeight: 22,
    letterSpacing: -0.5,
    color: colors.BLACK,
    borderBottomColor: colors.BLACK_WITH_OPACITY_1,
    borderTopWidth: 1,
    overflow: 'hidden',
    paddingTop: 11,
  },
  customerSperatorColor: {
    backgroundColor: colors.BLACK,
    height: 1,
    opacity: 0.2,
    marginLeft: 15,
    marginRight: 0,
    marginTop: 11,
  },
};
